#!/usr/bin/env python3
"""Optional task mirror for this skill's explicitly registered native assignments.
No decryption: replace only an exact registered agent_message with our own task text.
Unregistered requests and the original model routing remain untouched.
"""
import argparse
import hashlib
import importlib.util
import json
import re
from pathlib import Path
import sys
import threading
import time

LOCK = threading.Lock()


def record_path(directory, agent_path):
    return Path(directory) / (hashlib.sha256(agent_path.encode()).hexdigest() + '.json')


def translate(payload, directory, now=None):
    now = time.time() if now is None else now
    if not isinstance(payload.get('input'), list):
        return payload
    result = dict(payload)
    output = []
    for item in payload['input']:
        if not isinstance(item, dict) or item.get('type') != 'agent_message':
            output.append(item)
            continue
        recipient = item.get('recipient', '')
        # Generated by the runner: 128-bit UUID names keep registrations from
        # colliding with /root/worker in a different chat. Never accept generic names.
        if not isinstance(recipient, str) or not re.fullmatch(r'/root(?:/[a-z0-9_]+)*/mmw_[0-9a-f]{32}', recipient):
            output.append(item)
            continue
        path = record_path(directory, recipient)
        if not path.exists():
            output.append(item)
            continue
        with LOCK:
            record = json.loads(path.read_text())
            if record['model'] != payload.get('model'):
                output.append(item)
                continue
            if record['agent_path'] != recipient or record['author'] != item.get('author'):
                raise ValueError('Native bridge sender/recipient mismatch')
            if now >= record['expires_at'] or record.get('closed'):
                raise ValueError('Native task registration expired or closed')
            ident = item.get('id')
            if not ident:
                raise ValueError('Native task message has no identity')
            if record.get('message_id') not in (None, ident):
                raise ValueError('One assignment per native agent; register a new agent for a new round')
            if not record.get('message_id'):
                record['message_id'] = ident
                record['first_seen_at'] = now
            record['last_seen_at'] = now
            record['requests'] = record.get('requests', 0) + 1
            tmp = path.with_suffix('.tmp')
            tmp.write_text(json.dumps(record, ensure_ascii=False, indent=2) + '\n')
            tmp.replace(path)
        # This plaintext is supplied by the orchestrator when it registered its task.
        # It is not decoded from encrypted_content and does not replace unrelated history.
        output.append({'type': 'message', 'role': 'user', 'content': [
            {'type': 'input_text', 'text': 'Delegated assignment from ' + record['author'] + ':\n' + record['prompt']}
        ]})
    result['input'] = output
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--router', required=True)
    parser.add_argument('--registry', required=True)
    args, rest = parser.parse_known_args()
    spec = importlib.util.spec_from_file_location('original_model_router', args.router)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    normalize = module.normalize_history
    module.normalize_history = lambda payload, route: normalize(translate(payload, args.registry), route)
    sys.argv = [args.router] + rest
    module.main()


if __name__ == '__main__':
    main()
